/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andev_mediademo_awindownative_NativePlayer */
extern "C" {
    	#include "3rdparty/ffmpeg/include/libavcodec/avcodec.h"
    	#include "3rdparty/ffmpeg/include/libavformat/avformat.h"
    	#include "3rdparty/ffmpeg/include/libavutil/avutil.h"
    	#include "3rdparty/ffmpeg/include/libavutil/samplefmt.h"
    	#include "3rdparty/ffmpeg/include/libavutil/common.h"
    	#include "3rdparty/ffmpeg/include/libavutil/channel_layout.h"
    	#include "3rdparty/ffmpeg/include/libavutil/opt.h"
    	#include "3rdparty/ffmpeg/include/libavutil/log.h"
    	#include "3rdparty/ffmpeg/include/libavutil/imgutils.h"
    	#include "3rdparty/ffmpeg/include/libavutil/mathematics.h"
    	#include "3rdparty/ffmpeg/include/libswscale/swscale.h"
    	#include "3rdparty/ffmpeg/include/libswresample/swresample.h"
};

#ifndef _Included_com_andev_mediademo_awindownative_NativePlayer
#define _Included_com_andev_mediademo_awindownative_NativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andev_mediademo_awindownative_NativePlayer
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_andev_mediademo_awindownative_NativePlayer_playVideo
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
