/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andev_mediademo_learnjni_JniTest */
extern "C" {
    	#include "3rdparty/ffmpeg/include/libavcodec/avcodec.h"
    	#include "3rdparty/ffmpeg/include/libavformat/avformat.h"
    	#include "3rdparty/ffmpeg/include/libavutil/avutil.h"
    	#include "3rdparty/ffmpeg/include/libavutil/samplefmt.h"
    	#include "3rdparty/ffmpeg/include/libavutil/common.h"
    	#include "3rdparty/ffmpeg/include/libavutil/channel_layout.h"
    	#include "3rdparty/ffmpeg/include/libavutil/opt.h"
    	#include "3rdparty/ffmpeg/include/libavutil/log.h"
    	#include "3rdparty/ffmpeg/include/libavutil/imgutils.h"
    	#include "3rdparty/ffmpeg/include/libavutil/mathematics.h"
    	#include "3rdparty/ffmpeg/include/libswscale/swscale.h"
    	#include "3rdparty/ffmpeg/include/libswresample/swresample.h"
};

#ifndef _Included_com_andev_mediademo_learnjni_JniTest
#define _Included_com_andev_mediademo_learnjni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andev_mediademo_learnjni_JniTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andev_mediademo_learnjni_JniTest_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_andev_mediademo_learnjni_JniTest
 * Method:    testArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_andev_mediademo_learnjni_JniTest_testArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
